#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    vehicle = bld.path.name
    bld.ap_stlib(
        name=vehicle + 'urus',
        ap_vehicle='UNKNOWN',
        ap_libraries=[
        ],
    )

    bld.ap_program(
        program_name=vehicle,
        program_groups=['urusexamples'],
        use=vehicle + 'urus',
    )
